name: Node CI pipelines

on :
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Setup Node Env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installing Dependecies
        run: npm install
      - name: Testing cases
        run: npm test
