name: Pull Request CI

on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout trigger
        uses: actions/checkout@v5
      - name: Setup Environment
        uses: actions/setup-node@v5
        with: 
          node-version: 24
      - name: Checking Branch name
        run: echo "Workflow is running on ${{github.ref_name}}"
      - name: Installing Dependecies
        run: npm install
      - name: Test Running
        run: npm test
